# Generated by Django 3.2.10 on 2022-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_codeshareuser_current_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesharesession',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='codesharesession',
            name='sample_output',
        ),
        migrations.AddField(
            model_name='codesharesession',
            name='session_name',
            field=models.CharField(default='defaut', max_length=25),
            preserve_default=False,
        ),
    ]
