# Generated by Django 3.2.10 on 2022-01-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220116_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesharesession',
            name='joiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joiner', to='core.codeshareuser'),
        ),
        migrations.AlterField(
            model_name='codesharesession',
            name='problem_statement',
            field=models.TextField(null=True),
        ),
    ]
