# Generated by Django 3.2.10 on 2022-01-16 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('core', '0004_auto_20220116_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesharesession',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codesharesession',
            name='joiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joiner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CodeShareUser',
        ),
    ]
